### ISSUE TITLE
Camera is not able to connect

### ISSUE THREAD

**Issue by jlg89** [Sunoo/homebridge-smtp-motion#6]
Where do I start troubleshooting?

```
{
            "platform": "smtpMotion",
            "plugin_map": {
                "plugin_name": "homebridge-smtp-motion"
            },
            "name": "SMTP Motion",
            "smtp_port": 5000,
            "http_port": 8089
        }
```

In the homebridge-ffmpeg-camera config, "porthttp": 8089 and camera "name": "Gate Camera"

<img width="414" alt="Screen Shot 2020-07-31 at 12 20 26 PM" src="https://user-images.githubusercontent.com/10470394/89060205-3fc13280-d328-11ea-99e2-f77717e65bce.png">

**Comment by jlg89** [comment]
I can telnet to localhost at the SMTP port, and it appears to be working. But the camera doesn't like it. I can't find anything in any log files; is there a way to enable debug?

**Comment by Sunoo** [comment]
There is no real debug support currently in the plugin, I can look into possibly adding some soon. I wonder what your camera is expecting that it's not seeing. I didn't have a camera that did SMTP handy during development, so I just used a normal email client for testing.

I don't see anything obviously wrong in your config (especially if you're able to telnet into that port). The one thing I never tested was file attachments, maybe that's what's causing the failure. Could you try disabling that and see what happens? Especially given that the plugin doesn't do anything with it anyways.

**Comment by jlg89** [comment]
I tried with & without the attachment, wondering if that would make a difference. No change. I'm running this past the camera manufacturer too (Reolink) to see what they can tell me.

**Comment by Sunoo** [comment]
I'll take a look at adding in some debug logging. Does it actually trigger motion in HomeKit, despite showing a failure on the config page?

**Comment by Sunoo** [comment]
Okay, I think I found the problem. Whenever I tested, I was using anonymous access. I just tried attempting to authenticate, and it rejected the attempt, causing the email attempt to fail. I'm working on a fix for that now, as well as to pass some internal logging on to the Homebridge logs, to help with any future issues.

**Comment by Sunoo** [comment]
I just pushed v1.1.1 that fixes the issue I found with authentication, and also writes some additional logging when Homebridge is started in debug mode. I did not have a convenient way to test with attachments, so I haven't tested that yet.

Let me know if this gets things working for you.

**Comment by jlg89** [comment]
If I can figure out how to get HOOBS to update the plugin list...grr.

**Comment by jlg89** [comment]
Got it updated. Still doesn't work, same error as before. Not sure how to put HOOBS in debug mode.

**Comment by Sunoo** [comment]
Yea, I agree, I think watching all the SMTP traffic would be ideal. You can could slap together a quick proxy either using Netcat or a few lines of Node. I could probably write up instructions either later if needed.

At least the issue I fixed earlier did exist, and someone would have hit it if you hadn't.

**Comment by Sunoo** [comment]
Also, I'd highly recommend using the Homebridge image instead of HOOBS. HOOBS makes weird modifications that can cause lots of incompatibilities. And the way they operate just leaves a bad taste in my mouth for many reasons.

Anyways, according to their docs, you can run it in debug mode with `-d`: https://support.hoobs.org/docs/5e764e72e87d1e02b6c19d4c

**Comment by jlg89** [comment]
OK, get this. I installed tcpdump, ran "sudo tcpdump -vv -i eth0 'port 2525'", and tried the camera. Nothing even blipped in tcpdump. Which most likely means that the Reolink camera doesn't send the email itself, it sends a notification to its mother ship (in China) and the email is sent from there. I almost wish I didn't know this...

**Comment by Sunoo** [comment]
That’s unexpected, but would explain your issues, since obviously the server on your local network wouldn’t be reachable from their server.

It’s weird though, since SMTP is a pretty simple protocol, which is why it still shows up in some many cameras and things.

If your camera can do FTP uploads, I have a plugin that can create notifications from those too. Assuming that behaves sanely.

**Comment by jlg89** [comment]
I've really bent over backwards trying to give the Reolink a shot at integrating into Homebridge somehow, but it has fought me at every turn. This experience is making me swear off Reolink cameras, going to replace this one with a Dafang-hacked WyzeCam.

**Comment by Sunoo** [comment]
For what it’s worth, I’ve had very good luck with Dafang Hacks on the WyzeCam 2.
